# Generated by Django 5.1.6 on 2025-04-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InterviewResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("question_number", models.IntegerField()),
                ("question_text", models.TextField(blank=True, null=True)),
                ("answer_text", models.TextField(blank=True, null=True)),
                ("score", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["session_id", "question_number"],
                "unique_together": {("session_id", "question_number")},
            },
        ),
    ]
