# Generated by Django 5.1.6 on 2025-05-07 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fakeapp", "0002_intervieweedetails_intervieweeskill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intervieweedetails",
            name="average_score",
        ),
        migrations.RemoveField(
            model_name="intervieweedetails",
            name="question_count",
        ),
        migrations.CreateModel(
            name="resumebased_interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume_json", models.TextField(blank=True, null=True)),
                ("job_description", models.TextField(blank=True, null=True)),
                ("job_description_json", models.TextField(blank=True, null=True)),
                ("final_score", models.FloatField(blank=True, null=True)),
                ("technical_score", models.FloatField(blank=True, null=True)),
                ("behavioral_score", models.FloatField(blank=True, null=True)),
                ("project_score", models.FloatField(blank=True, null=True)),
                ("scenario_score", models.FloatField(blank=True, null=True)),
                (
                    "interviewee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to="fakeapp.intervieweedetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="skillbased_interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_count", models.IntegerField(default=0)),
                ("average_score", models.FloatField(blank=True, null=True)),
                (
                    "interviewee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="fakeapp.intervieweedetails",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="intervieweeskill",
            name="interviewee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="fakeapp.skillbased_interview",
            ),
        ),
    ]
