# Generated by Django 5.1.6 on 2025-05-07 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fakeapp", "0003_remove_intervieweedetails_average_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intervieweeskill",
            name="interviewee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviewee_skills",
                to="fakeapp.intervieweedetails",
            ),
        ),
    ]
