# Generated by Django 5.1.6 on 2025-05-09 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fakeapp", "0004_alter_intervieweeskill_interviewee"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewresponse",
            name="expected_answer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interviewresponse",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resumebased_interview",
            name="improvemen",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resumebased_interview",
            name="interview_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resumebased_interview",
            name="strengths",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resumebased_interview",
            name="weaknesses",
            field=models.TextField(blank=True, null=True),
        ),
    ]
