# Generated by Django 5.1.6 on 2025-05-10 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fakeapp", "0005_interviewresponse_expected_answer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resumebased_interview",
            old_name="improvemen",
            new_name="improvement",
        ),
    ]
